MVC/Areas/ComplectatorFace/Controllers/ComplectatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibsDb;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using LibsDb.LibsEntities;
using LibsMVC.Areas.ComplectatorFace;
using ASpbLibs.Areas.ComplectatorFace.Views.Complectator;
using ASpbLibs.Application.Abstraction;
using CoreApp.AppAPI;

namespace ASpbLibs.Areas.ComplectatorFace.Controllers
{
    [Area("ComplectatorFace")]
    public class ComplectatorController : UserSessionController<ComplectatorViewModel>
    {
        private readonly ComplectatorService _service;
        private readonly ApplicationDbContext _context;

        public ComplectatorController(ApplicationDbContext context, ComplectatorService service, APIAuthorization authorization) : base(authorization)
        {
            _service = service;
            _context = context;
        }

        public IActionResult ComplectatorHome()
        {
            ComplectatorViewModel model = GetModel();
            return View(model);
        }

        public override void InitModel(ComplectatorViewModel model)
        {
            Holder holder = _service.GetHolder();
            int id = holder.ID;
            Holder record = (from p in _context.Holders.Include(h => h.Liters) where p.ID == _service.GetHolder().ID select p).SingleOrDefault();
            model.Holder = record;
        }

        public IActionResult NavigateTo( string key )
        {
            ComplectatorViewModel model = GetModel();
            model.Active = key;
            return View("ComplectatorHome",model);
        }
    }
}

MVC/Areas/CuratorFace/Controllers/HoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibsDb;
using LibsDb.LibsEntities;

namespace ASpbLibs.Areas.CuratorFace.Controllers
{
    [Area("CuratorFace")]
    public class HoldersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HoldersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: HolderFace/Holders
        public async Task<IActionResult> Index()
        {
            var libsDbContext = _context.Holders;
            return View(await libsDbContext.ToListAsync());
        }

        // GET: HolderFace/Holders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var holder = await (from p in _context.Holders.Include(h => h.Liters) where p.ID == id select p).SingleOrDefaultAsync();                                
            if (holder == null)
            {
                return NotFound();
            }

            return View(holder);
        }

        // GET: HolderFace/Holders/Create
        public IActionResult Create()
        {
            ViewData["LibID"] = new SelectList(_context.Libs, "ID", "ID");
            return View();
        }

        // POST: HolderFace/Holders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Location,LibID")] Holder holder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(holder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LibID"] = new SelectList(_context.Libs, "ID", "ID", holder.LibID);
            return View(holder);
        }

        // GET: HolderFace/Holders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var holder = await (from p in _context.Holders where p.ID == id select p).SingleOrDefaultAsync();

            if (holder == null)
            {
                return NotFound();
            }
            ViewData["LibID"] = new SelectList(_context.Libs, "ID", "ID", holder.LibID);
            return View(holder);
        }

        // POST: HolderFace/Holders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Location,LibID")] Holder holder)
        {
            if (id != holder.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(holder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HolderExists(holder.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LibID"] = new SelectList(_context.Libs, "ID", "ID", holder.LibID);
            return View(holder);
        }

        // GET: HolderFace/Holders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var holder = await (from p in _context.Holders where p.ID == id select p).SingleOrDefaultAsync();

            if (holder == null)
            {
                return NotFound();
            }

            return View(holder);
        }

        // POST: HolderFace/Holders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var holder = await (from p in _context.Holders where p.ID == id select p).SingleOrDefaultAsync();

            _context.Holders.Remove(holder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HolderExists(int id)
        {
            return _context.Holders.Any(e => e.ID == id);
        }
    }
}

MVC/Areas/ReaderFace/Controllers/LitersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibsDb;
using LibsDb.LibsEntities;
using LibsMVC.Areas.ReaderFace.Views.Liters;
using CoreApp.AppAPI;
using ASpbLibs.Core.Services;
using ASpbLibs.Application.Abstraction;
using ASpbLibs.Core.Services.Libs;


namespace ASpbLibs.Areas.ReaderFace.Controllers
{
    [Area("ReaderFace")]
    public class LitersController : UserSessionController<LitersViewModel>
    {
      
        private readonly ApplicationDbContext _context;
        private readonly NotificationsService _notifications;
        private readonly CategoriesService _categories;


        public LitersController(
                CategoriesService categories, 
                NotificationsService notifications, 
                         
                ApplicationDbContext context, 
                APIAuthorization authorization) :base(authorization)
        {
          
            _context = context;
            _categories = categories;
            _notifications = notifications;
        }







        public override async Task<IActionResult> Index()
        {
            LitersViewModel model = GetModel();

            List<int> selectedCategoryIds = _categories.GetSelectedCategoryIds();
            model.Categories = _categories.GetCategoryHier();
            await UpdateModel();
            return View(model);
        }




        public IActionResult Checkout()
        {
            return RedirectToAction("Index","DeliveryOrder",new { 
                area="ReaderFace"
            });
        }


        public async Task<IActionResult> SetPage(int page)
        {
            var model = GetModel();
            model.CurrentPage = page;
            model = await UpdateModel();
            return View("Index",  model);
        }


        public async Task<IActionResult> RemoveFromOrder(int? id)
        {
            Liter liter = (from l in GetModel().Order where l.ID == id select l).SingleOrDefault();
            if (liter != null)
            {
                GetModel().Order.Remove(liter);
                (from f in _context.Liters.Include(l => l.Description) where f.ID==liter.ID select f).SingleOrDefault().Status=0;
                await _context.SaveChangesAsync();
            }
            return View("Index",await UpdateModel());
        }

        
        
        public async Task<IActionResult> AddToOrder(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            LitersViewModel model = GetModel();
            lock (model)
            {
                var liter = (from l in _context.Liters.Include(l => l.Description) where l.ID == id select l).SingleOrDefault();
                if (liter == null)
                {
                    return NotFound();
                }
                if (liter.Status != 0)
                {
                    _notifications.AddNotification(new NotificationMessage()
                    {
                        Title = liter.Description.Title + " уже занята другим читателем",
                        Type = "Error"
                    });
                }
                else
                {
                    liter.Status = 1;
                    model.Order.Add(liter);
                    _notifications.AddNotification(new NotificationMessage()
                    {
                        Title = liter.Description.Title + " добавлена в корзину заказа",
                        Type = "Success"
                    });
                    _context.SaveChanges();
                }
            }
            
         
            return View("Index", await UpdateModel());
        }


        /// <summary>
        /// Обновление страницы
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Update()
        {
            await UpdateModel();
            return View("Index",GetModel());
        }



        /// <summary>
        /// Выполнение поиска литературы
        /// </summary>
        /// <param name="fromRequest"> строка поиска </param>
        public async Task<IActionResult> Search( [Bind("SearchQuery")] LitersViewModel fromRequest)
        {
            string query = fromRequest.SearchQuery;
            LitersViewModel model = GetModel();
            model.SearchQuery = query;
            await UpdateModel();
            return View("Index", model);
        }


        private void UpdatePagesInModel(LitersViewModel model)
        {
            var dataset = model.All;
            model.TotalPages = (dataset.Count() % model.PageSize == 0) ?
                    (int)Math.Floor((decimal)(dataset.Count() / model.PageSize)) :
                    1 + (int)Math.Floor((decimal)(dataset.Count() / model.PageSize));
            int page = model.CurrentPage;
            int size = model.PageSize;
            model.Available = page == 1 ? dataset.Take(size).ToList() :
                    dataset
                    .Skip((page - 1) * size)
                    .Take(size).ToList();
        }


        private async Task<LitersViewModel> UpdateModel()
        {
            LitersViewModel model = GetModel();
            int size = model.PageSize;
            int page = model.CurrentPage;

            List<int> selectedCategoryIds = _categories.GetSelectedCategoryIds();
            model.All =
                (from p in _context.LiterDescriptions
                 where 
                   (String.IsNullOrEmpty(model.SearchQuery) || String.IsNullOrWhiteSpace(model.SearchQuery) || p.Title.ToLower().IndexOf(model.SearchQuery.ToLower()) != -1) 
                   && selectedCategoryIds.Contains(p.CategoryID)
                   && (p.Liters.Where(l=>l.Status==0).Count()>0)
                 select p).ToList();
            UpdatePagesInModel(model);
            model.All = (from p in _context.LiterDescriptions.Include(d => d.Liters) where (from pp in model.All select pp.ID).Contains(p.ID) select p).ToList();
            return model;
        }

        
        private bool LiterExists(int id)
        {
            return _context.Liters.Any(e => e.ID == id);
        }

        public override void InitModel(LitersViewModel model)
        {
           
        }
    }
}

MVC/Areas/ComplectatorFace/Views/Complectator/ComplectatorHome.cshtml
@model ASpbLibs.Areas.ComplectatorFace.Views.Complectator.ComplectatorViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>


    <div>
        <h4>Выдача литературы</h4>
        <hr />
        <dl class="row">
            <dt class="col-2">
                @Html.DisplayNameFor(model => model.Holder.Location)
            </dt>
            <dd class="col-10">
            
                @Html.DisplayFor(model => model.Holder.Location)
            </dd>
        </dl>
    </div>
    <div>
        
        <partial name="_TabbedPane" model="Model" />

    </div>

      
</div>

MVC/Areas/ComplectatorFace/Views/Complectator/_ComplectatorViewModel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MVC/Areas/ComplectatorFace/Views/Complectator/_DeliveryHistoryViewModel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MVC/Areas/ComplectatorFace/Views/Complectator/_DeliveryStatsViewModel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MVC/Areas/ComplectatorFace/Views/Complectator/_Holders.cshtml
@model IEnumerable<LibsDb.LibsEntities.Holder>

@{
    ViewData["Title"] = "Edit";
}

<h4> Места выдачи </h4>
<table class="table">
    <thead style="h-4">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>

                    <a asp-controller="Holders" asp-action="Details" asp-route-id="@item.ID">Перейти</a>

                </td>
            </tr>
        }
    </tbody>
</table>

MVC/Areas/ComplectatorFace/Views/Complectator/_Liters.cshtml
@model IEnumerable<LibsDb.LibsEntities.Liter>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description.Title)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description.Title)
            </td>
           
           
            <td>
              
                @item.Description.Overview
       
            </td>
        </tr>
        }
    </tbody>
</table>

MVC/Areas/ComplectatorFace/Views/Complectator/_LitersViewModel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MVC/Areas/ComplectatorFace/Views/Complectator/_TabbedPane.cshtml
@model ASpbLibs.Application.Abstraction.TabsView.TabsViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div>
    <div style="display: flex; flex-direction: row; flex-wrap: nowrap; width: 100%;">
        @foreach (string key in (new List<string>(Model.Nav.Keys)))
        {
            @if (key == ((string)Model.Active))
            {
                <a asp-action="NavigateTo" asp-route-key="@key">
                    <li class="list-group-item d-flex justify-content-between align-items-center active"
                        style="width: 225px; word-break: keep-all;">
                        @key
                    </li>
                </a>
            }
            else
            {
                <a asp-action="NavigateTo" asp-route-key="@key">
                    <li class="list-group-item d-flex justify-content-between align-items-center" style="width: 225px;  word-break: keep-all;">
                        @key
                    </li>
                </a>
            }
        }
    </div>
    <div>
        <partial name="_@Model.Nav[Model.Active].GetType().Name" model="@Model.Nav[Model.Active]"/>
    </div>
</div>