MVC/Areas/ReaderFace/Controllers/DeliveryFactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibsDb.LibsEntities;
using CoreApp.AppAPI;
using ASpbLibs.Areas.ReaderFace.Views.DeliveryFacts;
using ASpbLibs.Application.Abstraction;
using ASpbLibs.Core.Services;

namespace ASpbLibs.Areas.ReaderFace.Controllers
{
    [Area("ReaderFace")]
    public class DeliveryFactsController : UserSessionController<ReturnOrderViewModel>
    {
        private readonly ApplicationDbContext _context;
        private readonly APIAuthorization _authorization;
        private readonly NotificationsService _notifications;

        private readonly ReturnService _returns;

        public DeliveryFactsController(
                ReturnService returns,
          
                NotificationsService notifications,
                ApplicationDbContext context,
                APIAuthorization authorization) : base( authorization )
        {
            _context = context;
            _authorization = authorization;
            _notifications = notifications;
          
            _returns = returns;
        }
        

        public IActionResult NewOrder()
        {
            return View("ReturnOrder",NewModel()); 
        }

        public override void InitModel(ReturnOrderViewModel model)
        {
            model.Available = _returns.GetNowStoredItems(_authorization.Verify());
            model.Selected = new List<DeliveryFact>();
        }


        /// <summary>
        /// Добавление сведений о факте выдачи в заявку на возврат литературы
        /// </summary>
        /// <param name="id">идентификатор факта выдачи</param>
        /// <returns></returns>
        public IActionResult AddToOrder(int? id)
        {
            var model = GetModel();
            DeliveryFact fact = model.Available.Find(f => f.ID == id);
            if (fact != null)
            {
                _notifications.AddNotification(new NotificationMessage()
                {
                    Title = $"{fact.Literature.Description.Title} добавлена в корзину возврата"
                });
                model.Available.Remove(fact);
                model.Selected.Add(fact);
            }
            else
            {
                _notifications.AddNotification(new NotificationMessage()
                {
                    Type = "Error",
                    Title = $"Данная литература не числится за Вами"
                });
            }
            return View("ReturnOrder", model);
        }


        /// <summary>
        /// Исключение сведений о факте выдачи в заявку на возврат литературы
        /// </summary>
        /// <param name="id">идентификатор факта выдачи</param>
        /// <returns></returns>
        public IActionResult RemoveFromOrder(int? id)
        {
            var model = GetModel();
            DeliveryFact fact = model.Selected.Find(f => f.ID == id);
            if (fact != null)
            {
                model.Selected.Remove(fact);
                model.Available.Add(fact);
                _notifications.AddNotification(new NotificationMessage()
                {
                    Title = $"{fact.Literature.Description.Title} исключена из заявки на возврат"
                });
            }
            else
            {
                _notifications.AddNotification(new NotificationMessage()
                {
                    Type = "Error",
                    Title = $"Литературы нету в заявке на возврат"
                });
            }


            return View("ReturnOrder", model);
        }


        /// <summary>
        /// Завершение оформления заявки на возврат литературы
        /// </summary>
        /// <returns></returns>
        public IActionResult Checkout()
        {
            var model = GetModel();
            _returns.ReturnOrderCheckout(model.Selected);
            _notifications.AddNotification(new NotificationMessage()
            {
                Title = $"Оформление возврата литературы завершено"
            });
            return View("ReturnOrder", NewModel());
        }


  

    }
}

MVC/Areas/ReaderFace/Controllers/LitersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibsDb;
using LibsDb.LibsEntities;
using LibsMVC.Areas.ReaderFace.Views.Liters;
using CoreApp.AppAPI;
using ASpbLibs.Core.Services;
using ASpbLibs.Application.Abstraction;
using ASpbLibs.Core.Services.Libs;


namespace ASpbLibs.Areas.ReaderFace.Controllers
{
    [Area("ReaderFace")]
    public class LitersController : UserSessionController<LitersViewModel>
    {
      
        private readonly ApplicationDbContext _context;
        private readonly NotificationsService _notifications;
        private readonly CategoriesService _categories;


        public LitersController(
                CategoriesService categories, 
                NotificationsService notifications, 
                         
                ApplicationDbContext context, 
                APIAuthorization authorization) :base(authorization)
        {
          
            _context = context;
            _categories = categories;
            _notifications = notifications;
        }







        public override async Task<IActionResult> Index()
        {
            LitersViewModel model = GetModel();

            List<int> selectedCategoryIds = _categories.GetSelectedCategoryIds();
            model.Categories = _categories.GetCategoryHier();
            await UpdateModel();
            return View(model);
        }




        public IActionResult Checkout()
        {
            return RedirectToAction("Index","DeliveryOrder",new { 
                area="ReaderFace"
            });
        }


        public async Task<IActionResult> SetPage(int page)
        {
            var model = GetModel();
            model.CurrentPage = page;
            model = await UpdateModel();
            return View("Index",  model);
        }


        public async Task<IActionResult> RemoveFromOrder(int? id)
        {
            Liter liter = (from l in GetModel().Order where l.ID == id select l).SingleOrDefault();
            if (liter != null)
            {
                GetModel().Order.Remove(liter);
                (from f in _context.Liters.Include(l => l.Description) where f.ID==liter.ID select f).SingleOrDefault().Status=0;
                await _context.SaveChangesAsync();
            }
            return View("Index",await UpdateModel());
        }

        
        
        public async Task<IActionResult> AddToOrder(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            LitersViewModel model = GetModel();
            lock (model)
            {
                var liter = (from l in _context.Liters.Include(l => l.Description) where l.ID == id select l).SingleOrDefault();
                if (liter == null)
                {
                    return NotFound();
                }
                if (liter.Status != 0)
                {
                    _notifications.AddNotification(new NotificationMessage()
                    {
                        Title = liter.Description.Title + " уже занята другим читателем",
                        Type = "Error"
                    });
                }
                else
                {
                    liter.Status = 1;
                    model.Order.Add(liter);
                    _notifications.AddNotification(new NotificationMessage()
                    {
                        Title = liter.Description.Title + " добавлена в корзину заказа",
                        Type = "Success"
                    });
                    _context.SaveChanges();
                }
            }
            
         
            return View("Index", await UpdateModel());
        }


        /// <summary>
        /// Обновление страницы
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Update()
        {
            await UpdateModel();
            return View("Index",GetModel());
        }



        /// <summary>
        /// Выполнение поиска литературы
        /// </summary>
        /// <param name="fromRequest"> строка поиска </param>
        public async Task<IActionResult> Search( [Bind("SearchQuery")] LitersViewModel fromRequest)
        {
            string query = fromRequest.SearchQuery;
            LitersViewModel model = GetModel();
            model.SearchQuery = query;
            await UpdateModel();
            return View("Index", model);
        }


        private void UpdatePagesInModel(LitersViewModel model)
        {
            var dataset = model.All;
            model.TotalPages = (dataset.Count() % model.PageSize == 0) ?
                    (int)Math.Floor((decimal)(dataset.Count() / model.PageSize)) :
                    1 + (int)Math.Floor((decimal)(dataset.Count() / model.PageSize));
            int page = model.CurrentPage;
            int size = model.PageSize;
            model.Available = page == 1 ? dataset.Take(size).ToList() :
                    dataset
                    .Skip((page - 1) * size)
                    .Take(size).ToList();
        }


        private async Task<LitersViewModel> UpdateModel()
        {
            LitersViewModel model = GetModel();
            int size = model.PageSize;
            int page = model.CurrentPage;

            List<int> selectedCategoryIds = _categories.GetSelectedCategoryIds();
            model.All =
                (from p in _context.LiterDescriptions
                 where 
                   (String.IsNullOrEmpty(model.SearchQuery) || String.IsNullOrWhiteSpace(model.SearchQuery) || p.Title.ToLower().IndexOf(model.SearchQuery.ToLower()) != -1) 
                   && selectedCategoryIds.Contains(p.CategoryID)
                   && (p.Liters.Where(l=>l.Status==0).Count()>0)
                 select p).ToList();
            UpdatePagesInModel(model);
            model.All = (from p in _context.LiterDescriptions.Include(d => d.Liters) where (from pp in model.All select pp.ID).Contains(p.ID) select p).ToList();
            return model;
        }

        
        private bool LiterExists(int id)
        {
            return _context.Liters.Any(e => e.ID == id);
        }

        public override void InitModel(LitersViewModel model)
        {
           
        }
    }
}

MVC/Areas/ReaderFace/Views/DeliveryFacts/ReturnOrder.cshtml
@model ASpbLibs.Areas.ReaderFace.Views.DeliveryFacts.ReturnOrderViewModel
 
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
 
@{
    ViewData["Title"] = "Возврат литературы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<!-- далее сама страница -->
<div style="width: 100%;">

    <form asp-action="Search" style="width: 100%;">
        <div (submit)="onSearch( query.value )" (keypress)="onKeypress( $event )" style="display: flex; flex-direction: row; flex-wrap: nowrap; align-items: baseline; justify-content: baseline; ">
            <input class="form-control" list="inputSearchOptions" type="text"
                   asp-for="SearchQuery"
                   placeholder="Поиск" aria-label="Search" autofocus="true"
                   style="top: 0px; left: 0px; width: 100%;">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">поиск</button>
            <datalist id="inputSearchOptions">
                @foreach (var option in new string[] { })
                {
                    <option *ngFor="let option of options" [value]="@option"> @option </option>
                }
            </datalist>
        </div>
    </form>

    <div class="container" style="width: 100%;">
        <div class="row">
            <div class="col-lg-9" style="overflow-y: auto;">
                <div>
                
                        @if (Model.Available != null)
                        {
                            @foreach (LibsDb.LibsEntities.DeliveryFact fact in Model.Available)
                            {
                                
                                    <ul class="list-group">

                                        <li class="list-group-item"
                                            style="display: flex; flex-direction: row; flex-wrap: nowrap;">


                                            <img style="width: 220px; height: 220px;" src="/api/Resource/Use/@fact.Literature.Description.ImageID" />

                                            <div style="padding: 20px; width: 100%;">
                                                <h3>
                                                    <span class="badge badge-primary badge-pill">1</span>
                                                    @fact.Literature.Description.Title
                                                </h3>
                                                <p>@fact.Literature.Description.Overview</p>

                                                <a asp-area="ReaderFace" asp-controller="DeliveryFacts" asp-action="AddToOrder" asp-route-id="@fact.ID">
                                                    <button class="btn btn-primary"> в корзину </button>
                                                </a>

                                            </div>
                                        </li>



                                    </ul>
                                 

                            }
                        }
                   

                    @if (Model.TotalPages > 1)
                    {

                        <div>
                            <nav>
                                <ul class="pagination">

                                    @if (Model.CurrentPage != 1)
                                    {
                                        <li class="page-item">
                                            <a class="page-link"
                                               asp-area="ReaderFace" asp-controller="Liters" asp-action="SetPage"
                                               asp-route-page="@Model.PrevPage()">назад</a>
                                        </li>
                                    }
                                    <div style="max-width: 360px; overflow-x: hidden; display: flex; flex-direction: row; flex-wrap:  nowrap;">
                                        @for (int pageNumber = Math.Max(1, Model.CurrentPage - 3); pageNumber <= Math.Min(Model.TotalPages, Model.CurrentPage + 3); pageNumber++)
                                        {
                                            @if (Model.CurrentPage == pageNumber)
                                            {
                                                <li class="page-item active">
                                                    <a class="page-link" asp-area="ReaderFace" asp-controller="Liters" asp-action="SetPage" asp-route-page="@pageNumber"> @pageNumber  </a>
                                                </li>
                                            }
                                            else
                                            {
                                                <li class="page-item">
                                                    <a class="page-link" asp-area="ReaderFace" asp-controller="Liters" asp-action="SetPage" asp-route-page="@pageNumber"> @pageNumber  </a>
                                                </li>
                                            }
                                        }
                                    </div>

                                    @if (Model.CurrentPage != Model.TotalPages)
                                    {
                                        <li class="page-item">
                                            <a class="page-link"
                                               asp-area="ReaderFace" asp-controller="Liters" asp-action="SetPage"
                                               asp-route-page="@Model.NextPage()">вперёд</a>
                                        </li>
                                    }
                                </ul>
                            </nav>

                        </div>
                    }

                </div>
            </div>
            <div class="col-lg-3">
                <h3>Корзина возврата</h3>
                @foreach (var fact in Model.Selected)
                {


                    <div style="display: flex; flex-direction: row; flex-wrap: nowrap; width: 100%;">
                        <div>@fact.Literature.Description.Title</div>
                        <a asp-area="ReaderFace" asp-controller="DeliveryFacts" asp-action="RemoveFromOrder" asp-route-id="@fact.ID" style="justify-self: flex-end; margin-left: auto;">убрать</a>
                    </div>
                }

                <div>
                    <a asp-controller="DeliveryFacts"
                       asp-action="Checkout"
                       class="btn btn-primary"
                       style="width: 100%;">
                       оформить возврат  
                    </a>
                </div>

            </div>
        </div>
    </div>


</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}