MVC/Areas/AdminFace/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationDb.Entities;
using ASpbLibs.Application.Abstraction.BookView;
using ASpbLibs.Core.Services.CRUD;
using CoreApp.AppAPI;
 
using ASpbLibs.Application.Abstraction.SearchView;
using ASpbLibs.Core.Services;

namespace ASpbLibs.Areas.AdminFace.Controllers
{
    [Area("AdminFace")]
    public class NewsController : SearchViewController<News>
    {
        private readonly ApplicationDbContext _context;
        private readonly PageLayoutService _layout;

        public NewsController(ApplicationDbContext context, 
                CRUDProtocol crud,
                    PageLayoutService layout,
                APIAuthorization authorization) : base(authorization)
        {
            _context = context;
            _layout = layout;


        }


        public override IQueryable<News> GetAll(SearchViewModel<News> model)
        {
            _layout.ShowCategories();
            return _context.News.Where(n => model.SearchQuery == "" || n.Title.ToLower().IndexOf(model.SearchQuery.ToLower()) != -1).OrderByDescending(n => n.Time);
        }

        public override List<string> GetKeywords(string query)
        {
            HashSet<string> keywords = new HashSet<string>();
            List<string> titles =
                (from p in _context.News
                 where p.Title.ToLower().IndexOf(query) != -1
                 select p.Title).Take(10).ToList();
            foreach (string title in titles)
            {
                foreach (string word in new List<string>(title.ToLower().Split(' ', '.', ',', '!')))
                {
                    keywords.Add(word);
                }
            }
            return new List<string>(keywords);
        }

 

        public override string GetViewName()
        {
            return "Index";
        }


        /// <summary>
        /// Переход на страницу просмотра сведений о Новости
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.ID == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

    
        /// <summary>
        /// Переход на страницу добавления Новости
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View(new News()
            {
                Time = DateTime.Now
            });
        }


        /// <summary>
        /// Добавления Новости
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Time,ImageID,Href,Description")] News news)
        {
            if (ModelState.IsValid)
            {
                _context.Add(news);
                await _context.SaveChangesAsync();
                NewModel();
                return await SetPage(1);
            }
            return View(news);
        }


        /// <summary>
        /// Переход на страницу редактирования Новости
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            NewModel();
            return await SetPage(1);
        }


        /// <summary>
        /// Редактирование Новости
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Time,Image,Href,Description")] News news)
        {
            if (id != news.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

       
        /// <summary>
        /// Удаление Новости
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FirstOrDefaultAsync(m => m.ID == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        
        /// <summary>
        /// ПОдтверждение удаления Новости
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.FindAsync(id);
            _context.News.Remove(news);
            await _context.SaveChangesAsync();
            NewModel();
            return await SetPage(1);
        }


        /// <summary>
        /// Проверка наличия записи с заданным идентификатором
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.ID == id);
        }

     
    }
}

MVC/Areas/AdminFace/Views/News/Create.cshtml
@model ApplicationDb.Entities.News

@{
    ViewData["Title"] = "Добавление 'Новости'";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="width: 100%;">

    <h1>Добавление Новости</h1>    
    <hr />
    <form asp-area="AdminFace" asp-controller="News" asp-action="Create">
        <div class="container">
            <div class="row">

                <div class="col-8">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <input asp-for="Time" class="form-control" hidden="true" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Href" class="control-label"></label>
                        <input asp-for="Href" class="form-control" />
                        <span asp-validation-for="Href" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <input type="hidden" asp-for="ImageID" id="inputImageID">
                        <script>
                            function doUpload() {
                                console.log('doUpload');
                                const allFiles = document.getElementById("inputResource").files;
                                if (allFiles.length == 0) {
                                    alert("Не выбрано ни одного файла");
                                } else {
                                    console.log('upload begin');
                                    var uploadResponse = upload(allFiles.item(0), 'Продукт', 'image/png');
                                    console.log('upload end');
                                    var response = JSON.parse(uploadResponse);
                                    document.getElementById("inputImageID").value = response.id;
                                    document.getElementById("buttonImageOfPhoto").style.backgroundImage = $"URL(/api/Resource/Use/" + response.id + ")";
                                    console.log(uploadResponse);
                                }
                            }
                            function upload(file, name, mime) {
                                var request = new XMLHttpRequest();
                                request.open('POST', '/api/Resource/Create', false);
                                request.setRequestHeader("Resource-Name", name);
                                request.setRequestHeader("Mime-Type", mime);
                                request.setRequestHeader("Content-Type", "multipart/form-data");
                                request.send(file);
                                return request.responseText;
                            }
                        </script>
                        <button style="width: 220px; height: 220px;"
                                id="buttonImageOfPhoto"
                                onclick="event.preventDefault(); document.getElementById('inputResource').click();">
                            @if (Model.ImageID != null)
                            {
                                <script>
                                    document.getElementById('buttonImageOfPhoto').style.backgroundImage = 'URL(/api/Resource/Use/@Model.ImageID)';
                                </script>
                            }
                            else
                            {
                                <b>Загрузить изображение</b>
                            }

                        </button>
                        <input type="file" id="inputResource" hidden onchange="
                        function doUpload() {
                            console.log('doUpload');
                            const allFiles = document.getElementById('inputResource').files;
                            if (allFiles.length == 0) {
                                alert('Не выбрано ни одного файла');
                            } else {
                                console.log('upload begin');
                                var uploadResponse = upload(allFiles.item(0), 'Product', 'image/png');
                                console.log('upload end');
                                var response = JSON.parse(uploadResponse);
                                document.getElementById('inputImageID').value = response.id;
                                document.getElementById('buttonImageOfPhoto').style.backgroundImage = 'URL(/api/Resource/Use/' + response.id + ')';
                                console.log(uploadResponse);
                            }
                        }
                        function upload(file, name, mime) {
                            var request = new XMLHttpRequest();
                            request.open('POST', '/api/Resource/Create', false);
                            request.setRequestHeader('Resource-Name', name);
                            request.setRequestHeader('Mime-Type', mime);
                            request.setRequestHeader('Content-Type', 'multipart/form-data');
                            request.send(file);
                            return request.responseText;
                        }
                        doUpload(); ">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <input type="submit" value="Добавить" class="btn btn-primary" />
                    </div>
                </div>
            </div>

        </div>
    </form>

    <div>
        <a asp-action="Index">Вернуться к списку</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Areas/AdminFace/Views/News/Delete.cshtml
@model ApplicationDb.Entities.News

@{
    ViewData["Title"] = "Удаление 'Новости'";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Удаление 'Новости'</h1>


<div>
    <h3>Вы действительно хотите удалить Новость?</h3>
   
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        @if (Model.ImageID != null)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-10">
                <img src="/Resource/Use/@Model.ImageID" />
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Href)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Href)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index" asp-area="AdminFace" asp-controller="News" >Вернуться к списку</a>
    </form>
</div>

MVC/Areas/AdminFace/Views/News/Edit.cshtml
@model ApplicationDb.Entities.News

@{
    ViewData["Title"] = "Редактирование 'Новости'";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h1>Редактирование</h1>


    <hr />
    <form asp-action="Edit">
        <div class="row">
            <div class="col-8">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input asp-for="Time" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Href" class="control-label"></label>
                    <input asp-for="Href" class="form-control" />
                    <span asp-validation-for="Href" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Сохранить" class="btn btn-primary" />
                </div>

            </div>
            <div class="col-4">
                <div class="form-group">
                    <input type="hidden" asp-for="ImageID" id="inputImageID">
                    <script>
                        function doUpload() {
                            console.log('doUpload');
                            const allFiles = document.getElementById("inputResource").files;
                            if (allFiles.length == 0) {
                                alert("Не выбрано ни одного файла");
                            } else {
                                console.log('upload begin');
                                var uploadResponse = upload(allFiles.item(0), 'Продукт', 'image/png');
                                console.log('upload end');
                                var response = JSON.parse(uploadResponse);
                                document.getElementById("inputImageID").value = response.id;
                                document.getElementById("buttonImageOfPhoto").style.backgroundImage = $"URL(/api/Resource/Use/" + response.id + ")";
                                console.log(uploadResponse);
                            }
                        }
                        function upload(file, name, mime) {
                            var request = new XMLHttpRequest();
                            request.open('POST', '/api/Resource/Create', false);
                            request.setRequestHeader("Resource-Name", name);
                            request.setRequestHeader("Mime-Type", mime);
                            request.setRequestHeader("Content-Type", "multipart/form-data");
                            request.send(file);
                            return request.responseText;
                        }
                    </script>
                    <button style="width: 220px; height: 220px;"
                            id="buttonImageOfPhoto"
                            onclick="event.preventDefault(); document.getElementById('inputResource').click();">
                        @if (Model.ImageID != null)
                        {
                            <script>
                                document.getElementById('buttonImageOfPhoto').style.backgroundImage = 'URL(/api/Resource/Use/@Model.ImageID)';
                            </script>
                        }
                        else
                        {

                        }

                    </button>
                    <input type="file" id="inputResource" hidden onchange="
                        function doUpload() {
                            console.log('doUpload');
                            const allFiles = document.getElementById('inputResource').files;
                            if (allFiles.length == 0) {
                                alert('Не выбрано ни одного файла');
                            } else {
                                console.log('upload begin');
                                var uploadResponse = upload(allFiles.item(0), 'Product', 'image/png');
                                console.log('upload end');
                                var response = JSON.parse(uploadResponse);
                                document.getElementById('inputImageID').value = response.id;
                                document.getElementById('buttonImageOfPhoto').style.backgroundImage = 'URL(/api/Resource/Use/' + response.id + ')';
                                console.log(uploadResponse);
                            }
                        }
                        function upload(file, name, mime) {
                            var request = new XMLHttpRequest();
                            request.open('POST', '/api/Resource/Create', false);
                            request.setRequestHeader('Resource-Name', name);
                            request.setRequestHeader('Mime-Type', mime);
                            request.setRequestHeader('Content-Type', 'multipart/form-data');
                            request.send(file);
                            return request.responseText;
                        }
                        doUpload(); ">
                </div>
            </div>
        </div>
    </form>

    <div>
        <a asp-action="Index" asp-area="AdminFace" asp-controller="News" >Вернуться к списку</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Areas/AdminFace/Views/News/Index.cshtml
@model ASpbLibs.Application.Abstraction.SearchView.SearchViewModel<ApplicationDb.Entities.News>

@{
    ViewData["Title"] = "Админитрирование раздела 'Новости'";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="width: 100%;">

    <h1>Новости</h1>

    <p>
        <a asp-area="AdminFace" asp-controller="News" asp-action="Create">Добавить</a>
    </p>


    <search href="/AdminFace/News" ng-init='query="@Model.SearchQuery"'></search>

    <div class="container">
        <div class="row">
            <div class="col-lg-9" style="overflow-y: auto;">
                <div>
                    <ul class="list-group">
                        @if (Model.Results != null)
                        {

                            @foreach (var item in Model.Results)
                            {
                                <li class="list-group-item" style="padding: 20px; width: 100%; display: flex; flex-direction: column; flex-wrap: nowrap;">

                                    <div style="padding: 18px; width: 100%; display: flex; flex-direction: row; flex-wrap: nowrap;">
                                        <div style="float: right; font-size: 20px; padding: 5px;"><b>@item.Time</b></div>
                                        <p style="font-size: 18px; padding: 5px;">@item.Title</p>
                                    </div>
                                    <div style="align-self: flex-end; margin-left: auto;">
                                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.ID">Редактировать</a>
                                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ID">Удалить</a>
                                    </div>
                                </li>
                            }
                        }
                        else
                        {
                            <p>Ничего не найдено</p>
                        }

                    </ul>
                    <div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <partial name="_Pagination" model="@Model" />
        </div>
    </div>


</div>