MVC/Areas/ComplectatorFace/Controllers/ComplectatorLitersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibsDb.LibsEntities;
using LibsMVC.Areas.ComplectatorFace;
using CoreApp.AppAPI;
using ASpbLibs.Core.Services.CRUD;
using ASpbLibs.Application.Abstraction.BookView;
using ASpbLibs.Core.Services;
using ASpbLibs.Application.Abstraction;
using System;
using ASpbLibs.Application.Abstraction.SearchView;

namespace ASpbLibs.Areas.ComplectatorFace.Controllers
{
    [Area("ComplectatorFace")]
    public class ComplectatorLitersController : BookViewController<Liter>
    {
        private readonly ApplicationDbContext _context;
        private readonly ComplectatorService _service;
        private readonly NotificationsService _notifications;

        public ComplectatorLitersController(
             
                APIAuthorization authorization, 
                NotificationsService notifications,
                ApplicationDbContext context, 
                ComplectatorService service) : base( authorization)
        {
            _context = context;                    
            _service = service;
            _notifications = notifications;           
        }

  
         

         


        // GET: HolderFace/Liters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var liter = await _context.Liters
                .Include(l => l.Holder)
                //.Include(l => l.Image)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (liter == null)
            {
                return NotFound();
            }

            return View(liter);
        }

        // GET: HolderFace/Liters/Create
        public IActionResult Create()
        {
            ViewData["HolderID"] = new SelectList(_context.Holders, "ID", "ID");
            ViewData["ImageID"] = new SelectList(_context.Resources, "ID", "Mime");
            return View(new Liter());
        }

        // POST: HolderFace/Liters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Overview,Year,Status,HolderID,ImageID,RFID")] Liter liter)
        {
            liter.Holder = _context.Holders.Find(_service.GetHolder().ID);
            if (ModelState.IsValid)
            {
                _context.Add(liter);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HolderID"] = new SelectList(_context.Holders, "ID", "ID", liter.HolderID);
            //ViewData["ImageID"] = new SelectList(_context.Resources, "ID", "Mime", liter.ImageID);
            return View(liter);
        }

        // GET: HolderFace/Liters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var liter = await _context.Liters.FindAsync(id);
            if (liter == null)
            {
                return NotFound();
            }
            
            ViewData["HolderID"] = new SelectList(_context.Holders, "ID", "ID", liter.HolderID);
            //ViewData["ImageID"] = new SelectList(_context.Resources, "ID", "Mime", liter.ImageID);
            return View(liter);
        }

        // POST: HolderFace/Liters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Overview,Year,Status,HolderID,ImageID,RFID")] Liter liter)
        {
            if (id != liter.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(liter);
                    await _context.SaveChangesAsync();
                    _notifications.AddNotification(new NotificationMessage()
                    {
                        Title = "Сведения о литературе успешно сохранены"
                    });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LiterExists(liter.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HolderID"] = new SelectList(_context.Holders, "ID", "ID", liter.HolderID);
            //ViewData["ImageID"] = new SelectList(_context.Resources, "ID", "Mime", liter.ImageID);
            return View(liter);
        }



        // GET: HolderFace/Liters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var liter = await _context.Liters
                .Include(l => l.Holder)
                //.Include(l => l.Image)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (liter == null)
            {
                return NotFound();
            }

            return View(liter);
        }

        // POST: HolderFace/Liters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var liter = await _context.Liters.FindAsync(id);
            _context.Liters.Remove(liter);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LiterExists(int id)
        {
            return _context.Liters.Any(e => e.ID == id);
        }

        public override IQueryable<Liter> GetAll()
        {
            return _context.Liters.Where(l => l.HolderID == _service.GetHolder().ID);
        }

        public override string GetViewName()
        {
            return "Index";
        }
    }
}

MVC/Areas/ReaderFace/Controllers/LitersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibsDb;
using LibsDb.LibsEntities;
using LibsMVC.Areas.ReaderFace.Views.Liters;
using CoreApp.AppAPI;
using ASpbLibs.Core.Services;
using ASpbLibs.Application.Abstraction;
using ASpbLibs.Core.Services.Libs;


namespace ASpbLibs.Areas.ReaderFace.Controllers
{
    [Area("ReaderFace")]
    public class LitersController : UserSessionController<LitersViewModel>
    {
      
        private readonly ApplicationDbContext _context;
        private readonly NotificationsService _notifications;
        private readonly CategoriesService _categories;


        public LitersController(
                CategoriesService categories, 
                NotificationsService notifications, 
                         
                ApplicationDbContext context, 
                APIAuthorization authorization) :base(authorization)
        {
          
            _context = context;
            _categories = categories;
            _notifications = notifications;
        }







        public override async Task<IActionResult> Index()
        {
            LitersViewModel model = GetModel();

            List<int> selectedCategoryIds = _categories.GetSelectedCategoryIds();
            model.Categories = _categories.GetCategoryHier();
            await UpdateModel();
            return View(model);
        }




        public IActionResult Checkout()
        {
            return RedirectToAction("Index","DeliveryOrder",new { 
                area="ReaderFace"
            });
        }


        public async Task<IActionResult> SetPage(int page)
        {
            var model = GetModel();
            model.CurrentPage = page;
            model = await UpdateModel();
            return View("Index",  model);
        }


        public async Task<IActionResult> RemoveFromOrder(int? id)
        {
            Liter liter = (from l in GetModel().Order where l.ID == id select l).SingleOrDefault();
            if (liter != null)
            {
                GetModel().Order.Remove(liter);
                (from f in _context.Liters.Include(l => l.Description) where f.ID==liter.ID select f).SingleOrDefault().Status=0;
                await _context.SaveChangesAsync();
            }
            return View("Index",await UpdateModel());
        }

        
        
        public async Task<IActionResult> AddToOrder(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            LitersViewModel model = GetModel();
            lock (model)
            {
                var liter = (from l in _context.Liters.Include(l => l.Description) where l.ID == id select l).SingleOrDefault();
                if (liter == null)
                {
                    return NotFound();
                }
                if (liter.Status != 0)
                {
                    _notifications.AddNotification(new NotificationMessage()
                    {
                        Title = liter.Description.Title + " уже занята другим читателем",
                        Type = "Error"
                    });
                }
                else
                {
                    liter.Status = 1;
                    model.Order.Add(liter);
                    _notifications.AddNotification(new NotificationMessage()
                    {
                        Title = liter.Description.Title + " добавлена в корзину заказа",
                        Type = "Success"
                    });
                    _context.SaveChanges();
                }
            }
            
         
            return View("Index", await UpdateModel());
        }


        /// <summary>
        /// Обновление страницы
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Update()
        {
            await UpdateModel();
            return View("Index",GetModel());
        }



        /// <summary>
        /// Выполнение поиска литературы
        /// </summary>
        /// <param name="fromRequest"> строка поиска </param>
        public async Task<IActionResult> Search( [Bind("SearchQuery")] LitersViewModel fromRequest)
        {
            string query = fromRequest.SearchQuery;
            LitersViewModel model = GetModel();
            model.SearchQuery = query;
            await UpdateModel();
            return View("Index", model);
        }


        private void UpdatePagesInModel(LitersViewModel model)
        {
            var dataset = model.All;
            model.TotalPages = (dataset.Count() % model.PageSize == 0) ?
                    (int)Math.Floor((decimal)(dataset.Count() / model.PageSize)) :
                    1 + (int)Math.Floor((decimal)(dataset.Count() / model.PageSize));
            int page = model.CurrentPage;
            int size = model.PageSize;
            model.Available = page == 1 ? dataset.Take(size).ToList() :
                    dataset
                    .Skip((page - 1) * size)
                    .Take(size).ToList();
        }


        private async Task<LitersViewModel> UpdateModel()
        {
            LitersViewModel model = GetModel();
            int size = model.PageSize;
            int page = model.CurrentPage;

            List<int> selectedCategoryIds = _categories.GetSelectedCategoryIds();
            model.All =
                (from p in _context.LiterDescriptions
                 where 
                   (String.IsNullOrEmpty(model.SearchQuery) || String.IsNullOrWhiteSpace(model.SearchQuery) || p.Title.ToLower().IndexOf(model.SearchQuery.ToLower()) != -1) 
                   && selectedCategoryIds.Contains(p.CategoryID)
                   && (p.Liters.Where(l=>l.Status==0).Count()>0)
                 select p).ToList();
            UpdatePagesInModel(model);
            model.All = (from p in _context.LiterDescriptions.Include(d => d.Liters) where (from pp in model.All select pp.ID).Contains(p.ID) select p).ToList();
            return model;
        }

        
        private bool LiterExists(int id)
        {
            return _context.Liters.Any(e => e.ID == id);
        }

        public override void InitModel(LitersViewModel model)
        {
           
        }
    }
}

MVC/Areas/ComplectatorFace/Views/ComplectatorLiters/Create.cshtml
@model LibsDb.LibsEntities.Liter
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Добавление литературы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <link href="~/libs/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <hr />
    <div class="row">
        <div class="col-8">
            <h1>Новая литература</h1>


            <form asp-action="Create">
                <input type="submit" value="Создать" class="btn btn-primary" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Description.Title" class="control-label"></label>
                    <input asp-for="Description.Title" class="form-control" />
                    <span asp-validation-for="Description.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description.Overview" class="control-label"></label>
                    <textarea asp-for="Description.Overview" class="form-control"></textarea>
                    <span asp-validation-for="Description.Overview" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description.Year" class="control-label"></label>
                    <input asp-for="Description.Year" class="form-control" />
                    <span asp-validation-for="Description.Year" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Создать" class="btn btn-primary" />
                </div>
            </form>
        </div>
        <div class="col-4">
            <form id="personForm" method="post">
                <input type="hidden" asp-for="Description.ImageID" id="inputPhotoID">
                <script>
                    function doUpload() {
                        console.log('doUpload');
                        const allFiles = document.getElementById("inputResource").files;
                        if (allFiles.length == 0) {
                            alert("Не выбрано ни одного файла");
                        } else {
                            console.log('upload begin');
                            var uploadResponse = upload(allFiles.item(0), 'Продукт', 'image/png');
                            console.log('upload end');
                            var response = JSON.parse(uploadResponse);
                            document.getElementById("inputPhotoID").value = response.id;
                            document.getElementById("buttonImageOfPhoto").style.backgroundImage = $"URL(/api/Resource/Use/" + response.id + ")";
                            console.log(uploadResponse);
                        }
                    }
                    function upload(file, name, mime) {
                        var request = new XMLHttpRequest();
                        request.open('POST', '/api/Resource/Create', false);
                        request.setRequestHeader("Resource-Name", name);
                        request.setRequestHeader("Mime-Type", mime);
                        request.setRequestHeader("Content-Type", "multipart/form-data");
                        request.send(file);
                        return request.responseText;
                    }
                </script>
                <button style="width: 220px; height: 220px;"
                        id="buttonImageOfPhoto"
                        onclick="event.preventDefault(); document.getElementById('inputResource').click();">
                    @if (Model.Description != null && Model.Description.ImageID != null)
                    {
                        <script>
                        document.getElementById('buttonImageOfPhoto').style.backgroundImage = 'URL(/api/Resource/Use/@Model.Description.ImageID)';
                        </script>
                    }
                    else
                    {

                    }

                </button>
                <input type="file" id="inputResource" hidden onchange="
                function doUpload() {
                    console.log('doUpload');
                    const allFiles = document.getElementById('inputResource').files;
                    if (allFiles.length == 0) {
                        alert('Не выбрано ни одного файла');
                    } else {
                        console.log('upload begin');
                        var uploadResponse = upload(allFiles.item(0), 'Product', 'image/png');
                        console.log('upload end');
                        var response = JSON.parse(uploadResponse);
                        document.getElementById('inputPhotoID').value = response.id;
                        document.getElementById('buttonImageOfPhoto').style.backgroundImage = 'URL(/api/Resource/Use/' + response.id + ')';
                        console.log(uploadResponse);
                    }
                }
                function upload(file, name, mime) {
                    var request = new XMLHttpRequest();
                    request.open('POST', '/api/Resource/Create', false);
                    request.setRequestHeader('Resource-Name', name);
                    request.setRequestHeader('Mime-Type', mime);
                    request.setRequestHeader('Content-Type', 'multipart/form-data');
                    request.send(file);
                    return request.responseText;
                }
                doUpload(); ">
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Вернуться к списку</a>
    </div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Areas/ComplectatorFace/Views/ComplectatorLiters/Delete.cshtml
@model LibsDb.LibsEntities.Liter
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Удаление литературы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>


    <h1>Удаление литературы</h1>

    <h3>Вы действительно хотите удалить литературу?</h3>
    <div>
        <h4>Liter</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Overview)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Overview)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Year)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Year)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Holder)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Holder.ID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Image)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Image.Mime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RFID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RFID)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="ID" />
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            <a asp-action="Index">Вернуться к списку</a>
        </form>
    </div>

</div>

MVC/Areas/ComplectatorFace/Views/ComplectatorLiters/Details.cshtml
@model LibsDb.LibsEntities.Liter
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Сведения о литературе";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>

    <h1>Сведения о литературе</h1>

    <div>

        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Overview)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Overview)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Year)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Year)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Holder)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Holder.ID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Image)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Image.Mime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RFID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RFID)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ID">Редактировать</a> |
        <a asp-action="Index">Вернуться к списку</a>
    </div>

</div>

MVC/Areas/ComplectatorFace/Views/ComplectatorLiters/Index.cshtml
@model ASpbLibs.Application.Abstraction.BookView.BookViewModel<LibsDb.LibsEntities.Liter>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Доступная литература";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="width: 100%;">
    <div>
        <a asp-controller="ComplectatorLiters" asp-action="Create">Добавить</a>
    </div>

    <!-- поисковая строка -->
    <div style="width: 100%;">
        <div (submit)="onSearch( query.value )" style="display: flex; flex-direction: row; flex-wrap: nowrap; align-items: baseline; justify-content: baseline; ">
            <input class="form-control" list="inputSearchOptions" type="text"
                   placeholder="Поиск" aria-label="Search" autofocus="true" #query
                   style="top: 0px; left: 0px; width: 100%;">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">поиск</button>
            <datalist id="inputSearchOptions">
                @foreach (var option in new string[] { })
                {
                    <option *ngFor="let option of options"> @option </option>
                }
            </datalist>
        </div>

    </div>



    <ul class="list-group" style="width: 100%;">
        
        @foreach (var item in Model.Results)
        {

            <li class="list-group-item"
                style="margin: 20px; display: flex; flex-direction: row; flex-wrap: nowrap;">
                <partial name="_@item.GetType().Name" model="item"></partial>

            </li>
        }
    </ul>

    <!-- постраничная навигация -->
    <nav>
        <ul class="pagination">

            @if (Model.TotalPages > 1)
            {
                @if (Model.CurrentPage != 1)
                {
                    <li class="page-item">
                        <a class="page-link"
                           asp-action="SetPage"
                           asp-route-page="@Model.PrevPage()">назад</a>
                    </li>
                }
                <div style="max-width: 360px; overflow-x: hidden; display: flex; flex-direction: row; flex-wrap:  nowrap;">
                    @for (int pageNumber = Math.Max(1, Model.CurrentPage - 3); pageNumber <= Math.Min(Model.TotalPages, Model.CurrentPage + 3); pageNumber++)
                    {
                        @if (Model.CurrentPage == pageNumber)
                        {
                            <li class="page-item active">
                                <a class="page-link" asp-action="SetPage" asp-route-page="@pageNumber"> @pageNumber  </a>
                            </li>
                        }
                        else
                        {
                            <li class="page-item">
                                <a class="page-link" asp-action="SetPage" asp-route-page="@pageNumber"> @pageNumber  </a>
                            </li>
                        }
                    }
                </div>

                @if (Model.CurrentPage != Model.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link"
                           asp-action="SetPage"
                           asp-route-page="@Model.NextPage()">вперёд</a>
                    </li>
                }
            }
        </ul>
    </nav>

</div>

MVC/Areas/ComplectatorFace/Views/ComplectatorLiters/_Liter.cshtml
@model LibsDb.LibsEntities.Liter
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Сведения о литературе";
}
@{
    Layout = null;
}

<div>

    <h4> @Html.DisplayFor(model => model.Description.Title)</h4>

    <div>

        <hr />
        <dl class="row">
        
         
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Overview)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Overview)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description.Year)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description.Year)
            </dd>
     
        
       
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RFID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RFID)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Delete" asp-route-id="@Model.ID">Удалить</a>|
        <a asp-action="Edit" asp-route-id="@Model.ID">Редактировать</a>
    </div>

</div>